services:
  website:
    image: jacob987/twitch-stats:latest
    container_name: website
    build:
      context: ../website
      dockerfile: ../website/docker/prd.Dockerfile
    expose:
      - "3000"
    restart: unless-stopped
    networks:
      - streamhub-network
    environment:
      - NODE_ENV=production
    env_file:
      - ../website/.env
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../certbot/conf:/etc/letsencrypt:ro
      - ../certbot/www:/var/www/certbot:ro
    depends_on:
      - website
    restart: unless-stopped
    networks:
      - streamhub-network
  certbot:
    image: certbot/certbot
    volumes:
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
  twitch-bot:
    container_name: twitch-bot
    image: jacob987/twitch-stats-bot:latest
    build:
      context: ../twitch-bot
      dockerfile: ../twitch-bot/docker/prd.Dockerfile
    restart: unless-stopped
    env_file:
      - ../twitch-bot/.env
    networks:
      - streamhub-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
networks:
  streamhub-network:
    driver: bridge
    name: streamhub-network